version: '3.4'

services:
  server:
    ports:
      - "5001:443"
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=CERT_PASSWORD # change CERT_PASSWORD
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/aspnetapp.pfx
    volumes:
      - CERT_EXPORT_PATH:/root/.aspnet/https:ro # change CERT_EXPORT_PATH