version: '3.4'

services:
  db:
    build: ./samples/Database
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=PASSWORD12345!
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
  server:
    build:
      context: .
      dockerfile: ./samples/Server/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Testing
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - db